site_name: On-Demend
site_url: https://on-demend.github.io/On-Demend/
site_description: On-Demand AWS
site_author: On-Demand
repo_url: https://github.com/On-Demend/On-Demend
repo_name: On-Demend/On-Demend
edit_uri: edit/main/docs/
language: en
nav:
  - "Home": index.md
  - "CI/CD":
    - "CodeDeploy": "CI&CD/CodeDeploy/ECS.md"
  - "EC2":
    - Systemd: EC2/systemd.md
  - "ECS":
    - Docker: ECS/docker.md
  - "EKS":
    - Installation: EKS/install.md
  - "Logging":
    - Fluentbit: Logging/fluentbit.md
  
  - "Getting Started":
    - "HTML/CSS":
      - "HTML": "Getting Started/HTML/html.md"
      - "CSS": "Getting Started/HTML/css.md"
    - "Linux":
      - "Commands": "Getting Started/Linux/Command.md"
    - "Network":
      - "IP & Subnet": "Getting Started/Network/IP.md"
      - "Protocols": "Getting Started/Network/Protocols.md"
      - "HTTP": "Getting Started/Network/HTTP.md"
  - "Etc Tools":
    - "AWS-Nuke": "ETC Tools/AWS-Nuke/default.md"
theme:
  language: ko
  name: material
  logo: "logos/on-demend.png"
  favicon: "logos/on-demend.png"
  icon:
    repo: fontawesome/brands/github
  font:
    code: Roboto Mono
  palette:
    theme:
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 라이트 모드로 전환

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: 시스템 설정 모드로 전환
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.follow
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.tracking
    - search.share
    - navigation.footer
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - tags:
      enabled: true
      listings: false

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
copyright: Copyright &copy; 2025 On-Demend
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/On-Demend
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ondemend?_gl=1*6ghh16*_gcl_au*MTM4OTg1NzU2NC4xNzQ0OTU0NTc1*_ga*MzA1OTk1NTExLjE3NDQ5NTQ1NzY.*_ga_XJWPQMJYHQ*czE3NDk0NDc3NjMkbzMkZzEkdDE3NDk0NDgxNDkkajU5JGwwJGgw