site_name: On-Demend
site_url: https://junki1108.github.io/On-Demend/
site_description: On-Demand AWS
site_author: Junki1108
repo_url: https://github.com/Junki1108/On-Demend
repo_name: Junki1108/On-Demend
edit_uri: edit/main/docs/
language: ko
nav:
  - "홈 | Home": index.md
  - "로깅 | Logging":
    - Fluentbit: Logging/fluentbit.md
  - "EC2":
    - Systemd: EC2/systemd.md
  - "ECS":
    - Docker: ECS/docker.md
  - "EKS":
    - Installation: EKS/install.md
  - "DB-A":
    - "04.14": "NoAWS/DB-A/0414s.md"
    - "05.08": "NoAWS/DB-A/0508s.md"
  - "Protection":
    - "04.15": "NoAWS/Protection/0415s.md"
    - "04.17-1": "NoAWS/Protection/0417-1.md"
    - "04.17-2": "NoAWS/Protection/0417-2.md"
  - "*비공개 - 이세찬이 멍청한 이유를 아십니까?": "양세찬/stu.md"
  - "<p style='color: lime; transition: 0.5s;'>이상한 사람들</p>": "etc/b.md"
theme:
  name: dracula
  logo: logo.png
  favicon: favicon.svg