site_name: On-Demend
site_url: https://junki1108.github.io/On-Demend/
site_description: On-Demand AWS
site_author: Junki1108
repo_url: https://github.com/Junki1108/On-Demend
repo_name: On-Demend/On-Demend
edit_uri: edit/main/docs/
language: ko
nav:
  - "홈 | Home": index.md
  - "로깅 | Logging":
    - Fluentbit: Logging/fluentbit.md
  - "EC2":
    - Systemd: EC2/systemd.md
  - "ECS":
    - Docker: ECS/docker.md
  - "EKS":
    - Installation: EKS/install.md
  - "CI/CD":
    - "CodeDeploy": "CI&CD/CodeDeploy/ECS.md"
  - "Getting Started":
    - "HTML/CSS":
      - "HTML": "Getting Started/HTML/html.md"
      - "CSS": "Getting Started/HTML/css.md"
    - "Linux":
      - "Commands": "Getting Started/Linux/Command.md"
    - "Network":
      - "IP & Subnet": "Getting Started/Network/IP.md"
      - "Protocols": "Getting Started/Network/Protocols.md"
      - "HTTP": "Getting Started/Network/HTTP.md"
  - "Etc Tools":
    - "AWS-Nuke": "ETC Tools/AWS-Nuke/default.md"
theme:
  name: dracula
  logo: logo.png
  favicon: favicon.svg