site_name: On-Demend
site_url: https://on-demend.github.io/On-Demend/
site_description: On-Demand AWS
site_author: On-Demand
repo_url: https://github.com/On-Demand/On-Demend
repo_name: On-Demend/On-Demend
edit_uri: edit/main/docs/
language: en
nav:
  - "Home": index.md
  - "CI/CD":
    - "CodeDeploy": "CI&CD/CodeDeploy/ECS.md"
  - "EC2":
    - Systemd: EC2/systemd.md
  - "ECS":
    - Docker: ECS/docker.md
  - "EKS":
    - Installation: EKS/install.md
  - "Logging":
    - Fluentbit: Logging/fluentbit.md
  
  - "Getting Started":
    - "HTML/CSS":
      - "HTML": "Getting Started/HTML/html.md"
      - "CSS": "Getting Started/HTML/css.md"
    - "Linux":
      - "Commands": "Getting Started/Linux/Command.md"
    - "Network":
      - "IP & Subnet": "Getting Started/Network/IP.md"
      - "Protocols": "Getting Started/Network/Protocols.md"
      - "HTTP": "Getting Started/Network/HTTP.md"
  - "Etc Tools":
    - "AWS-Nuke": "ETC Tools/AWS-Nuke/default.md"
theme:
  name: material
  logo: logo.png
  favicon: favicon.svg
  palette:
    - scheme: default
      primary: green
      accent: teal
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - tags

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde